name: Type checks

on: [push]

jobs:
  test:
    name: Run type checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install mypy

    - name: Run mypy checks
      run: mypy patchwork/
